#!/usr/bin/env bash
# redeploy.sh — rebuild and redeploy the Roleplayer stack after a code change.
# Run on the Swarm manager Pi from the project root.
set -euo pipefail

STACK="roleplayer"
IMAGE="roleplayer:latest"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Must match setup.sh's NAS_IP/DATA_ROOT so the TLS cert ends up in the same
# place the running container expects it (DB_PATH's sibling "tls" dir).
NAS_IP="${NAS_IP:-192.168.178.62}"
MOUNT_POINT="/volume1/cloudstorage"
DATA_ROOT="${MOUNT_POINT}/docker-swarm-data"
TLS_HOSTNAME="${TLS_HOSTNAME:-pi1}"

# ── 0. Load Pi-local secrets/config ───────────────────────────────────────────
# .env is gitignored and lives only on the Pi — it is never overwritten by a
# git pull. Put host-specific values here (ASR_URL, DISCORD_BOT_TOKEN, MinIO
# credentials, …). See .env.example for the list of supported variables.
ENV_FILE="${SCRIPT_DIR}/.env"
if [[ -f "${ENV_FILE}" ]]; then
  echo "==> Loading ${ENV_FILE} …"
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

# ── 0b. Ensure the TLS certificate exists ─────────────────────────────────────
# HttpsConnectorConfig silently disables HTTPS (port 3502) if no cert/key are
# found under <DATA_ROOT>/roleplayer/tls/ — this only gets generated by
# setup.sh, so a redeploy-only workflow (no setup.sh re-run) would otherwise
# leave HTTPS unreachable forever, even though the port is published. Generate
# it here too if missing, so redeploy.sh alone is enough to keep HTTPS working.
ensure_tls_certificate() {
  local tls_dir="${DATA_ROOT}/roleplayer/tls"
  local cert="${tls_dir}/cert.pem"
  local key="${tls_dir}/key.pem"

  if [[ -f "${cert}" && -f "${key}" ]]; then
    return
  fi

  echo "==> No TLS certificate found at ${cert} — generating one for '${TLS_HOSTNAME}' …"
  sudo mkdir -p "${tls_dir}"
  sudo chmod 777 "${tls_dir}"

  local lan_ip
  lan_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  local san="DNS:${TLS_HOSTNAME},DNS:localhost,IP:127.0.0.1"
  [[ -n "${lan_ip}" ]] && san="${san},IP:${lan_ip}"

  sudo openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes \
    -keyout "${key}" -out "${cert}" \
    -subj "/CN=${TLS_HOSTNAME}" \
    -addext "subjectAltName=${san}" \
    >/dev/null 2>&1

  sudo chmod 644 "${cert}" "${key}"
  echo "==> TLS certificate created: ${cert}"
}
ensure_tls_certificate

# ── 1. Build image (ARM64 for Raspberry Pi) ───────────────────────────────────
echo "==> Building ${IMAGE} …"
docker build --platform linux/arm64 -t "${IMAGE}" "${SCRIPT_DIR}"

# ── 2. Deploy stack ───────────────────────────────────────────────────────────
# Swarm cannot hot-swap a running service between networks via
# `stack deploy`/`service update` — network attachments are fixed at
# service-creation time. If the previously deployed roleplayer_app is not
# already attached to the predefined "host" network (e.g. it's still on the
# old "internal" overlay network, or on an auto-created "roleplayer_default"
# overlay network from an earlier failed attempt at `network_mode: host` —
# which Swarm silently ignores instead of honoring), remove the whole stack
# first so it gets recreated cleanly with the current network config.
if docker service inspect "${STACK}_app" >/dev/null 2>&1; then
  ATTACHED_NETWORK_IDS="$(docker service inspect --format '{{range .Spec.TaskTemplate.Networks}}{{.Target}} {{end}}' "${STACK}_app" 2>/dev/null || true)"
  HOST_NETWORK_ID="$(docker network inspect --format '{{.Id}}' host 2>/dev/null || true)"
  NEEDS_RECREATE=true
  if [[ -n "${HOST_NETWORK_ID}" ]]; then
    for network_id in ${ATTACHED_NETWORK_IDS}; do
      [[ "${network_id}" == "${HOST_NETWORK_ID}" ]] && NEEDS_RECREATE=false
    done
  fi
  if [[ "${NEEDS_RECREATE}" == "true" ]]; then
    echo "==> Existing ${STACK}_app service is not attached to the predefined 'host' network but the"
    echo "    compose file now requires it — Swarm can't migrate this in place. Removing the stack so"
    echo "    it can be recreated cleanly …"
    docker stack rm "${STACK}"
    echo "==> Waiting for the stack's services to fully tear down …"
    for _ in $(seq 1 30); do
      docker service inspect "${STACK}_app" >/dev/null 2>&1 || break
      sleep 2
    done
    # Removing a stack also tears down its overlay network(s) asynchronously,
    # *after* the services are gone. If `stack deploy` runs again before that
    # teardown finishes, it can see the network still present at the moment
    # it lists networks (skipping re-creation) but find it gone by the time
    # it actually creates a dependent service — surfacing as
    # "network roleplayer_internal not found" (or "roleplayer_default not
    # found") while creating other services. Wait for the networks to
    # disappear too, not just the services.
    echo "==> Waiting for the stack's overlay networks to fully tear down …"
    for network_name in "${STACK}_internal" "${STACK}_default"; do
      for _ in $(seq 1 30); do
        docker network inspect "${network_name}" >/dev/null 2>&1 || break
        sleep 2
      done
    done
  fi
fi

echo "==> Deploying stack '${STACK}' …"
deploy_stack() {
  MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY:-roleplayer}" \
  MINIO_SECRET_KEY="${MINIO_SECRET_KEY:-roleplayer123}" \
  ASR_URL="${ASR_URL:-http://Stefans-PC:9090}" \
  DISCORD_BOT_TOKEN="${DISCORD_BOT_TOKEN:-}" \
  docker stack deploy -c "${SCRIPT_DIR}/docker-compose.yml" "${STACK}"
}
# A prior stack removal's network teardown can still be finishing up even
# after the wait loop above gives up (worst case ~60s) — retry once after a
# short pause instead of failing outright on the classic
# "network roleplayer_internal not found" race.
if ! deploy_stack; then
  echo "==> Stack deploy failed (possibly a network teardown race) — retrying once in 10s …"
  sleep 10
  deploy_stack
fi

# ── 3. Force the app service onto the freshly built image ────────────────────
# docker stack deploy with a ":latest" tag does NOT restart already-running
# services. Since the tag string never changes between builds, Swarm considers
# the service spec unchanged and skips rolling new tasks — --force makes it
# restart the task so the freshly built image is actually used.
#
# If a previous deploy failed its healthcheck, the service's update state can
# be stuck at "paused" — a plain --force update is then rejected/ignored by
# Swarm, so clear that first by resuming/rolling back to a clean state.
UPDATE_STATE="$(docker service inspect --format '{{.UpdateStatus.State}}' "${STACK}_app" 2>/dev/null || true)"
if [[ "${UPDATE_STATE}" == "paused" ]]; then
  echo "==> Service update was paused (likely a failed healthcheck) — rolling back first …"
  docker service rollback "${STACK}_app" || true
fi

echo "==> Updating app service to new image …"
docker service update --force --image "${IMAGE}" "${STACK}_app"

# ── 4. Verify the rollout actually converged instead of pausing again ────────
echo "==> Waiting for rollout to converge …"
for _ in $(seq 1 30); do
  STATE="$(docker service inspect --format '{{.UpdateStatus.State}}' "${STACK}_app" 2>/dev/null || echo "unknown")"
  if [[ "${STATE}" == "completed" || -z "${STATE}" ]]; then
    break
  fi
  if [[ "${STATE}" == "paused" ]]; then
    echo ""
    echo "✗ Rollout paused again — the new image is failing its healthcheck."
    echo "  Check logs with: docker service logs ${STACK}_app"
    docker stack ps "${STACK}" --no-trunc
    exit 1
  fi
  sleep 2
done

echo ""
echo "✓ Deployment complete. Reachable at:"
echo "    http://pi1:3002   (no microphone access)"
echo "    https://pi1:3502  (self-signed cert; accept the one-time browser warning; needed for microphone recording)"
echo ""
docker stack ps "${STACK}" --no-trunc
